### ISSUE TITLE
Figure out a better name!

### ISSUE THREAD

**Issue by TomasTomecek** [user-cont/tool#1]
My wild ideas:
 * w
 * pheasant
 * helper
 * samo

**Comment by lachmanfrantisek** [comment]
> w

Is there any idea behind that? Nevertheless, it would useful.

**Comment by lachmanfrantisek** [comment]
> samo

+1

**Comment by TomasTomecek** [comment]
> Is there any idea behind that? Nevertheless, it would useful.

It's just shortcut for w[orkflow]. I got the idea from [this tool - z](https://github.com/rupa/z).
