### ISSUE TITLE
RFE: Ever heard of IGitt ?

### ISSUE THREAD

**Issue by jpopelka** [user-cont/tool#27]
https://github.com/GitMateIO/IGitt
https://igitt.gitmate.io

It might simplify our [services](https://github.com/user-cont/tool/tree/master/tool/services).

(Spotted in @fridex's [Kebechet](https://github.com/thoth-station/kebechet/blob/master/kebechet/source_management.py))

**Comment by TomasTomecek** [comment]
Looks pretty good! The project seems to be active (on gitlab).

**Comment by TomasTomecek** [comment]
Closing since we have ogr now.
